stages:
    - build
before_script:
build_prod:
    stage: build
    script:
        - echo $env:CI_JOB_ID
        - echo $env:GITLAB_USER_EMAIL
        - pwd
        
    only:
        refs:
            - master
            - schedules
    tags: 
        - prod
        - production
