stages:
    - install
    - test
    - deploy
before_script:
    - git clean -fd

install:
    stage: install
    script: npm install
    
    only:
        refs:
            - master
            - schedules
    tags: 
        - prod
        - production

test:
    stage: test
    script: npm run test:junit
    dependenciese:
        - install
    artifacts: 
        reports:
            junit: junit.xml

    only:
        refs:
            - master
            - schedules
    tags: 
        - prod
        - production

deploy:
    stage: deploy
    script:
        - rm -r /wikipedia-medication-extractor
        - mkdir /wikipedia-medication-extractor
        - cp -a ./public/ /wikipedia-medication-extractor/public
        - cp -a ./src/ /wikipedia-medication-extractor/src
        - cp -a ./.gitignore /wikipedia-medication-extractor/.gitignore
        - cp -a ./.gitlab-ci.yml /wikipedia-medication-extractor/.gitlab-ci.yml
        - cp -a ./package-lock.json /wikipedia-medication-extractor/package-lock.json
        - cp -a ./jsDocConf.json /wikipedia-medication-extractor/jsDocConf.json
        - cp -a ./package.json /wikipedia-medication-extractor/package.json
        - cp -a ./README.md /wikipedia-medication-extractor/README.md
        - cp -a ./google-credentials.json /wikipedia-medication-extractor/google-credentials.json
        - cp -a ./server.env /wikipedia-medication-extractor/server.env
        - cd /wikipedia-medication-extractor
        - npm install

        - systemctl stop wikiapi
        - systemctl start wikiapi
        
    only:
        refs:
            - master
            - schedules
    tags: 
        - prod
        - production
