cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

stages:
    - install
    - test
    - deploy

install:
    stage: install
    before_script: 
        - git clean -fd
    script: npm install

    only:
        refs:
            - master
            - test
            - schedules
    tags: 
        - prod
        - production

test:
    stage: test
    needs: [install]
    script: 
        - npm run test:junit
    artifacts: 
        reports:
            cobertura: coverage/cobertura-coverage.xml
            junit: junit.xml

    only:
        refs:
            - master
            - test
            - schedules
    tags: 
        - prod
        - production

deploy:
    stage: deploy
    needs: [test]
    script:
        - rm -r /wikipedia-medication-extractor
        - mkdir /wikipedia-medication-extractor
        - cp -a ./public/ /wikipedia-medication-extractor/public
        - cp -a ./src/ /wikipedia-medication-extractor/src
        - cp -a ./.gitignore /wikipedia-medication-extractor/.gitignore
        - cp -a ./.gitlab-ci.yml /wikipedia-medication-extractor/.gitlab-ci.yml
        - cp -a ./package-lock.json /wikipedia-medication-extractor/package-lock.json
        - cp -a ./jsDocConf.json /wikipedia-medication-extractor/jsDocConf.json
        - cp -a ./package.json /wikipedia-medication-extractor/package.json
        - cp -a ./README.md /wikipedia-medication-extractor/README.md
        - cp -a ./google-credentials.json /wikipedia-medication-extractor/google-credentials.json
        - cp -a ./config.js /wikipedia-medication-extractor/config.js
        - cp -a ./jest.config.js /wikipedia-medication-extractor/jest.config.js
        - cd /wikipedia-medication-extractor
        - npm install

        - systemctl stop wikiapi
        - systemctl start wikiapi
        
    only:
        refs:
            - master
            - schedules
    tags: 
        - prod
        - production
