stages:
    - build
before_script:
    - git clean -fd
build_prod:
    stage: build
    script:
        - pwd
        - cd /wikipedia-medication-extractor
        - npm install
        - npm run build
        - systemctl restart wikiapi
        
    only:
        refs:
            - master
            - schedules
    tags: 
        - prod
        - production
