stages:
    - build
before_script:
    - npm install
build_prod:
    stage: build
    script:
        - echo $env:CI_JOB_ID
        - echo $env:GITLAB_USER_EMAIL
        - pwd
        - npm run build
        - cp -a ./pages/ /wikipedia-medication-extractor/pages
        - cp -a ./.next/ /wikipedia-medication-extractor/.next
        - cp -a ./.gitignore /wikipedia-medication-extractor/.gitignore
        - cp -a ./.gitlab-ci.yml /wikipedia-medication-extractor/.gitlab-ci.yml
        - cp -a ./package-lock.json /wikipedia-medication-extractor/package-lock.json
        - cp -a ./package.json /wikipedia-medication-extractor/package.json
        - cp -a ./README.md /ot/wikipedia-medication-extractor/README.md
        - cp -a ./public /wikipedia-medication-extractor/public
        - cd /wikipedia-medication-extractor
        - npm install
        - systemctl restart wikiapi
        
    only:
        refs:
            - master
            - schedules
    tags: 
        - prod
        - production
