stages:
    - build
before_script:
    - git clean -fd
build_prod:
    stage: build
    script:
        - pwd
        - npm install
        - npm run build
        - rm -r /wikipedia-medication-extractor/pages
        - cp -a ./pages/ /wikipedia-medication-extractor/pages
        - cp -a ./.gitignore /wikipedia-medication-extractor/.gitignore
        - cp -a ./.gitlab-ci.yml /wikipedia-medication-extractor/.gitlab-ci.yml
        - cp -a ./package-lock.json /wikipedia-medication-extractor/package-lock.json
        - cp -a ./package.json /wikipedia-medication-extractor/package.json
        - cp -a ./README.md /wikipedia-medication-extractor/README.md
       
        - cd /wikipedia-medication-extractor
        - npm install
        - systemctl stop wikiapi
        - npm run build
        - systemctl start wikiapi
        
    only:
        refs:
            - master
            - schedules
    tags: 
        - prod
        - production
