const axios = require('axios');

const api_url= "https://wikiapi.mheine94.now.sh/v2"
const local_url = "http://localhost:3000/api/v2"
const local = true;
const getUrl = ()=> local?local_url:api_url
module.exports = async (req, res) => {
  try {
    let query = req.query.query?req.query.query:''
    let  lang = req.query.lang?req.query.lang:'en'
    let body  = req.body

    if (query == undefined | query == null) {
      res.status(501)
    }
    res.status(200)
    
      let result;

      if(body){
        let queryWords;
        if(body.query){
          console.log("Post body query:",body.query)
          console.log("Post lang:",body.lang)
          queryWords=body.query;
          lang= body.lang
        }else{
          queryWords = body.replace(/\r/g,'').split(/\n/)
        }
        console.log("Post body query list",queryWords)
       // if(queryWords.lengh>100){
       //   console.log("Big query... Doing a splitrequest",queryWords)
       //   result = await splitRequest(queryWords,lang)
       // }else{
          result = await mutliSearch(queryWords,lang)
       // }
       
      }else{
        let queryWords = query.split(',');
        console.log("Get query list",queryWords)
        ///jooo
        if (queryWords.length > 1) {
          result = await mutliSearch(queryWords,lang)
        } else {
          result = await apiSearch(query,lang)
        }
      }
      
  
      try {
  
        let jsonpretty = JSON.stringify(result, null, 4)
        res.header("Content-Type",'application/json');
        res.send(jsonpretty)
  
      } catch (exjson) {
  
        res.json(result)
      }
    } catch (ex) {
      console.log(ex)
      res.json({
        error: ex,
        query: query
      })
    }
  }
  
  Array.prototype.unique = function () {
    return this.filter(function (value, index, self) {
      return self.indexOf(value) === index;
    });
  }
  
  const https = require('https')
  
  async function mutliSearch(querySplit,lang) {
    let queryPromises = querySplit.map(q => new Promise(async(resolve)=>{
      let res = await apiSearch(q,lang)
      resolve( {query:q,result:res})
    }))
    let queryResults = await Promise.all(queryPromises)
    let innDict = {}
    queryResults.forEach((res) => {
      let v=res.result
    
      if(v.error|| !v.inn){
        if(innDict["unknown"]==null || innDict["unknown"]==undefined){
          innDict["unknown"]=[]
        }
        innDict["unknown"].push(res.query)
      }else{
        if (v.inn && innDict[v.inn.toLowerCase()]) {
          if(v.ingredientClass){
            Array.prototype.push.apply(innDict[v.inn.toLowerCase()].ingredientClass, v.ingredientClass)
            innDict[v.inn.toLowerCase()].ingredientClass = innDict[v.inn.toLowerCase()].ingredientClass.unique()
          }
          if(v.formula){
            Array.prototype.push.apply(innDict[v.inn.toLowerCase()].formula, v.formula)
            innDict[v.inn.toLowerCase()].formula = innDict[v.inn.toLowerCase()].formula.unique()
          }
          if(v.tradenames){
            Array.prototype.push.apply(innDict[v.inn.toLowerCase()].tradenames, v.tradenames)
            innDict[v.inn.toLowerCase()].tradenames = innDict[v.inn.toLowerCase()].tradenames.unique()
          }
          if(v.cas){
            Array.prototype.push.apply(innDict[v.inn.toLowerCase()].cas, v.cas)
            innDict[v.inn.toLowerCase()].cas = innDict[v.inn.toLowerCase()].cas.unique()
          }
          if(v.atc){
            Array.prototype.push.apply(innDict[v.inn.toLowerCase()].atc, v.atc)
            innDict[v.inn.toLowerCase()].atc = innDict[v.inn.toLowerCase()].atc.unique()
          }
        } else {
          if (v.inn) {
            let entry =
            {
              "inn": v.inn.toLowerCase(),
              "ingredientClass": [],
              "tradenames": [],
              "formula": [],
              "cas": [],
              "atc": []
            }
            if(v.ingredientClass) {
              Array.prototype.push.apply(entry.ingredientClass, v.ingredientClass)
              entry.ingredientClass = entry.ingredientClass.unique()
            }
            if(v.formula) {
              Array.prototype.push.apply(entry.formula, v.formula)
              entry.formula = entry.formula.unique()
            }
            if(v.cas){
              Array.prototype.push.apply(entry.cas, v.cas)
              entry.cas = entry.cas.unique()
            }
            if(v.atc){
              Array.prototype.push.apply(entry.atc, v.atc)
              entry.atc = entry.atc.unique()
            }
            if (v.tradenames) {
              Array.prototype.push.apply(entry.tradenames, v.tradenames)
              entry.tradenames = entry.tradenames.unique()
            }
            innDict[v.inn.toLowerCase()] = entry
          }
        }
      }

    })
    return innDict
  }
  
  

  async function post(url,text,retries=0) {
    var config = {
        headers: {
            'Content-Type': 'text/plain'
        }
    };
    let currentTry =1;
    while(currentTry < retries){
      try {
        const res = await axios.post(url, text,config);
        console.log(`Status: ${res.status}`);
        console.log('Body: ', res.data);
        return res
    } catch (err) {
        console.log("Retry "+currentTry+++"/"+retries)
    }
    }
    return null
  }

  async function splitRequest(queryWords,lang){
    let lastIndex = 0;
    let results = []

    for(i=100;i<queryWords.length;i+=100){
      if(i>queryWords.lengh-1){
          let chunk = queryWords.slice(lastIndex,queryWords.lengh-1)
          let requestText = chunk.reduce((peviousValue,currentValue,currentIndex,array)=>{
              return peviousValue+=`\n${currentValue}`
          })
          //
          results.push(post(getUrl()+'?lang='+lang,requestText,10))
      }else{
          let chunk = queryWords.slice(lastIndex,i)
          lastIndex=i
          let requestText = chunk.reduce((peviousValue,currentValue,currentIndex,array)=>{
            return peviousValue+=`\n${currentValue}`
          })
          results.push(post(getUrl()+'?lang='+lang,requestText,10))
      }
    }
    let res = await Promise.all(results)
    console.log("Got all requests back...Merging")
    let mergedResults = mergeResults(res.filter(res=>res!=null).map(res=>res.data?res.data:{}))
           
    return mergedResults
  }

  function mergeResults(results){
        let mergedResults = results.reduce((previousValue, currentValue) => {
            Object.keys(currentValue).forEach((currentValue_key)=>{
                if(previousValue[currentValue_key]!=null &&previousValue[currentValue_key]!=undefined){
                    if(previousValue[currentValue_key].tradenames!=null){
                        previousValue[currentValue_key].tradenames= previousValue[currentValue_key].tradenames.concat(currentValue[currentValue_key].tradenames).unique()
                    }else{
                        previousValue[currentValue_key].tradenames = currentValue[currentValue_key].tradenames
                    }
                }else{
                    previousValue[currentValue_key]=currentValue[currentValue_key]
                }
            })
            return previousValue
        })
    
        return mergedResults
  }



const mergeTest = '[{"amikacin": {"inn": "amikacin","ingredientClass": [ "Aminoglykosid-Antibiotikum" ], "tradenames": ["Suppiluppi","muppi"],"formula": [   "C22H43N5O13"        ],        "cas": [            "37517-28-5"        ],        "atc": [            "D06AX12J01GB06S01AA21"        ]    }},	{"amikacin": {        "inn": "amikacin","ingredientClass": [  "Aminoglykosid-Antibiotikum"  ], "tradenames": ["Suppiluppi","bongoSpasti","mangobango"],  "formula": [  "C22H43N5O13"  ], "cas": [    "37517-28-5"  ],  "atc": [  "D06AX12J01GB06S01AA21"   ]  }},  {"amoxicillin": {    "inn": "amoxicillin",        "ingredientClass": [          "β-Lactam-Antibiotika" ],"tradenames": [],"formula": [    "C16H19N3O5S"      ], "cas": [      "26787-78-0",    "61336-70-7 (Amoxicillin-Trihydrat)",    "34642-77-8 (Amoxicillin-Natrium)"],"atc": [        "J01CA04"   ]    }}]'


  
  function search(term,lang) {
    return get('https://'+ lang +'.wikipedia.org/w/api.php?action=query&list=search&srsearch=' + term + '&utf8=&format=json')
  }
  
  function getPageInfo(pageId) {
    return get('https://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&rvsection=0&format=json&pageids=' + pageId + '&redirects=true')
  }
  function getPageContent(pageid) {
    return get('https://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvslots=*&rvprop=content&format=json&formatversion=2&pageids=' + pageid)
  }
  function getHtmlPage(title,lang){
    return get('https://'+ lang +'.wikipedia.org/wiki/'+title)
  }
  
  const cheerio = require('cheerio')
  
  function get(url) {
    return new Promise((resolve, reject) => {
      https.get(url, (resp) => {
        let data = '';
  
        resp.on('data', (chunk) => {
          data += chunk;
        });
        resp.on('end', () => {
          try {
            resolve(data)
          } catch (ex) {
            reject(data)
          }
        })
      })
    })
  }
  
  async function apiSearch(word,lang) {
    try{
    if (word == undefined || word == null || word === "") {
      return getErrorResponse("No search word", word)
    }
    let res = await search(word,lang)
    
    let searchresult = JSON.parse(res)
    if (searchresult && searchresult.query && searchresult.query.searchinfo && searchresult.query.searchinfo.totalhits > 0) {
      if (searchresult.query.search[0]) {
        try {
          let page = searchresult.query.search[0]
          let pageTitle = page.title

          let inn= null
          let tradenames = []
          let ingredientClass = []
          let casn =  []
          let atcc= []
          let formula = []

          // check for link to a "brand names"-page and move on with the INN-page to get all information
          if (pageTitle.includes(' brand names')) {
            // depcrecated: tradenames.push(word)
            pageTitle = page.title.substring(0, page.title.search(' brand names'))
          }

          let pageHtml = await getHtmlPage(pageTitle,lang)
          const $ = cheerio.load(pageHtml);
          
          let hasInfobox = $('.infobox').length > 0
          if(!hasInfobox)
            throw new Error('Page: "' + pageTitle + '" has no infobox.')

          
          switch(lang){
            case 'de':
              inn = $('a[title="Internationaler Freiname"]','.infobox').parent().next('td')[0].childNodes[0].data.replace(/\n/g,'')
              
              let isList_inredientClass = $('a[title="Wirkstoffklasse"]','.infobox').parent().next('td').children('ul').length > 0
              if(isList_inredientClass) {
                ingredientClass = $('a[title="Wirkstoffklasse"]','.infobox').parent().next('td').find('li').map((i,el)=> {
                  return $(el).text()
                }).toArray()
              } else {
                ingredientClass.push($('a[title="Wirkstoffklasse"]','.infobox').parent().next('td').find('a').first().text().replace(/\n/g,''))
              }
              let isList_casn = $('a[title="CAS-Nummer"]','.infobox').parent().next('td').children('ul').length > 0
              if(isList_casn){
                casn = $('a[title="CAS-Nummer"]','.infobox').parent().next('td').find('li').map((i,el)=> {
                  return $(el).text()
                }).toArray()
              }else{
                casn.push( $('a[title="CAS-Nummer"]','.infobox').parent().next('td')[0].childNodes[0].data.replace(/\n/g,''))
              }
              let isList_atc = $('a[title="Anatomisch-Therapeutisch-Chemisches Klassifikationssystem"]','.infobox').parent().next('td').children('ul').length > 0
              if(isList_atc){
                atcc = $('a[title="Anatomisch-Therapeutisch-Chemisches Klassifikationssystem"]','.infobox').parent().next('td').find('li').map((i,el)=> {
                  return $(el).text()
                }).toArray()
              }else{
                atcc.push($('a[title="Anatomisch-Therapeutisch-Chemisches Klassifikationssystem"]','.infobox').parent().next('td').find('a').text().replace(/\n/g,''))
              }
              
              let isList_formula = $('a[title="Summenformel"]','.infobox').parent().next('td').children('ul').length > 0
              if(isList_formula){
                formula = $('a[title="Summenformel"]','.infobox').parent().next('td').find('li').map((i,el)=> {
                  return $(el).text()
                }).toArray()
              }else{
                formula.push($('a[title="Summenformel"]','.infobox').parent().next('td').text().replace(/\n/g,''))
              }
              break;
            default:
              
              //$('caption span','.infobox')[0].childNodes[0].data
              inn= $('caption','.infobox').text()
              if(!tradenames) {
                tradenames = $('a[title="Drug nomenclature"]','.infobox').parent().next('td')[0].childNodes[0].data.split(',').map(s=>s.trim()).filter(s=> s.length>0)
              }
              casn = $('a[title="CAS Registry Number"]','.infobox').parent().next('td').find('li').map((i,el)=> {
                return $($(el).find('span')[0]).text()
              }).toArray()
              atcc = $('a[title="Anatomical Therapeutic Chemical Classification System"]','.infobox').parent().next('td').find('li').children().filter('a').map((i,el)=> {
                return $(el).text()
              }).toArray()
              formula.push($('a[title="Chemical formula"]','.infobox').parent().next('td').text().replace(/\n/g,''))
          }
         
          if(word.toLowerCase() !== inn.toLowerCase()){
            tradenames = []
            tradenames.push(word)
          }

          let result = {
            "tradenames": tradenames,
            "ingredientClass": ingredientClass,
            "cas": casn,
            "atc": atcc,
            "formula": formula,
            "inn": inn
          }
          return result
          console.log(result)
        } catch (ex) {
          return getErrorResponse(ex.message, word)
        }
      } else {
        return getErrorResponse("Nothing was found on wikipedia", word)
      }
    } else {
      return getErrorResponse("Nothing was found on wikipedia", word)
      
    }
  }catch (ex){
    return getErrorResponse(ex.message, word)
  }
  }
  
  function getErrorResponse(message,query){
    return {
      error: message,
      query: query
    }
  }
  
  apiSearch('aspirin', 'en').then((res)=>{
    console.log(res)
    console.log("Done...")
 }) 
  


  const test = [
    "Amikacin",
    "Amoxicillin",
    "Ampicillin",
    "Azidocillin",
    "Azithromycin",
    "Aztreonam",
    "Bacampicillin",
    "Benzylpenicillin",
    "Benzylpenicillin-Benzathin",
    "Cefacetril",
    "Cefadroxil",
    "Cefalexin",
    "Cefaloridin",
    "Cefalotin",
    "Cefamandol",
    "Cefamandolnafat",
    "Cefapirin",
    "Cefazedon",
    "Cefazolin",
    "Cefepim",
    "Cefiderocol",
    "Cefixim",
    "Cefodizim",
    "Cefotaxim",
    "Cefotiam",
    "Cefoxitin",
    "Cefpodoxim",
    "Cefpodoximproxetil",
    "Cefradin",
    "Cefroxadin",
    "Ceftazidim",
    "Ceftibuten",
    "Ceftiofur",
    "Ceftobiprol",
    "Ceftolozan",
    "Ceftriaxon",
    "Cefuroxim",
    "Chloramphenicol",
    "Chlortetracyclin",
    "Cilastatin",
    "Ciprofloxacin",
    "Clarithromycin",
    "Clavulansäure",
    "Clindamycin",
    "Cloxacillin",
    "Colistin",
    "Cotrimoxazol",
    "Dalbavancin",
    "Daptomycin",
    "Doripenem",
    "Doxycyclin",
    "Enoxacin",
    "Ertapenem",
    "Erythromycin",
    "Faropenem",
    "Fleroxacin",
    "Flucloxacillin",
    "Fosfomycin",
    "Gentamicin",
    "Grepafloxacin",
    "Iclaprim",
    "Imipenem",
    "Josamycin",
    "Kanamycine",
    "Lefamulin",
    "Levofloxacin",
    "Lincomycin",
    "Linezolid",
    "Lomefloxacin",
    "Loracarbef",
    "Meropenem",
    "Methicillin",
    "Metronidazol",
    "Mezlocillin",
    "Minocyclin",
    "Moxifloxacin",
    "Nalidixinsäure",
    "Neomycin",
    "Netilmicin",
    "Nitrofurantoin",
    "Nitroxolin",
    "Norfloxacin",
    "Ofloxacin",
    "Oxacillin",
    "Oxytetracyclin",
    "Phenoxymethylpenicillin",
    "Pipemidsäure",
    "Piperacillin",
    "Pivmecillinam",
    "Pristinamycin",
    "Propicillin",
    "Roxithromycin",
    "Spectinomycin",
    "Spiramycin",
    "Streptomycin",
    "Sulbactam",
    "Sulfadiazin",
    "Sulfadimidin",
    "Sulfamerazin",
    "Sulfamethoxazol",
    "Sulfanilamid",
    "Sultamicillin",
    "Tazobactam",
    "Tebipenempivoxil",
    "Tedizolid",
    "Teicoplanin",
    "Telithromycin",
    "Tetracyclin",
    "Tigecyclin",
    "Trimethoprim",
    "Vancomycin"
  ];

  let test_Big=["Kaliumchlorid",
  "AT10",
  "AARANE",
  "ABASAGLAR",
  "ACC",
  "ACC",
  "ADDEL TRACE",
  "ADRENALIN",
  "AERIUS",
  "ANESDERM",
  "ANESDERM",
  "ANTICHOLIUM",
  "ASS",
  "ASS",
  "AZILECT",
  "Acarbose",
  "Accu",
  "Accu",
  "Acemit",
  "AciVision",
  "Aciclovir",
  "Aciclovir",
  "Aciclovir",
  "Acic",
  "Acimethin",
  "Actilyse",
  "Actilyse",
  "Actilyse",
  "Actrapid",
  "Adalat",
  "Adenoscan",
  "Adrekar",
  "Adrenalin",
  "Advagraf",
  "Advagraf",
  "Advagraf",
  "Advagraf",
  "Advantan",
  "Advantan",
  "Advantan",
  "Advantan",
  "Aethoxysklerol",
  "Aethoxysklerol",
  "Aethoxysklerol",
  "Akineton",
  "Akineton",
  "Akineton",
  "Akrinor",
  "Albiomin",
  "Albothyl",
  "Aldactone",
  "Alendronsäure",
  "Alfuzosin",
  "Alkohol",
  "Allopurinol",
  "Allopurinol",
  "Alphagan",
  "Alprazolam",
  "Alupent",
  "Alvesco",
  "AmBisome",
  "AmbroHEXAL",
  "Ambroxol",
  "Ambroxol",
  "Amikacin",
  "Amikacin",
  "Amineurin",
  "Amineurin",
  "Amineurin",
  "Aminoplasmal",
  "Aminopäd",
  "Aminoven",
  "Amiodaron",
  "Amiodaron",
  "Amitriptylin",
  "Amlodipin",
  "Amlodipin",
  "Amoclav",
  "Amoclav",
  "AmoxClav",
  "Amoxi",
  "Amoxi",
  "AmoxiClav",
  "AmoxiHEXAL",
  "AmoxiHEXAL",
  "AmoxiHEXAL",
  "Ampho",
  "Ampho",
  "Ampho",
  "Ampicillin",
  "Ampicillin",
  "Ampicillin",
  "Ampuwa",
  "Anaesthesulf",
  "Anafranil",
  "Anafranil",
  "Ancotil",
  "Androcur",
  "Antifect",
  "Antifungol",
  "Antifungol",
  "Antifungol",
  "Antifungol",
  "Antra",
  "Antra",
  "Apidra",
  "Aplona",
  "Apomorphin",
  "Aponal",
  "Aprepitant",
  "Aprepitant",
  "Aprovel",
  "Aprovel",
  "Aprovel",
  "Apydan",
  "Apydan",
  "Aqua",
  "Aqua",
  "Aqua",
  "Aqua",
  "Aqua",
  "Aqua",
  "Aqua",
  "Aranesp",
  "Aranesp",
  "Aranesp",
  "Aranesp",
  "Aranesp",
  "Aranesp",
  "Aranesp",
  "Aranesp",
  "Aranesp",
  "Arilin",
  "Arimidex",
  "Aripiprazol",
  "Aripiprazol",
  "Aripiprazol",
  "Arixtra",
  "Arixtra",
  "Arixtra",
  "Arixtra",
  "Artelac",
  "Arterenol",
  "Arterenol",
  "Aspirin",
  "Aspirin",
  "Atarax",
  "Atemkalk",
  "Atenolol",
  "Atenolol",
  "Atorvastatin",
  "Atorvastatin",
  "Atorvastatin",
  "Atosil",
  "Atosil",
  "Atosil",
  "Atovaquon",
  "Atracurium",
  "Atropinsulfat",
  "Atropinsulfat",
  "Attends",
  "Aureomycin",
  "Aurorix",
  "Avamys",
  "Axura",
  "Azathioprin",
  "Azithromycin",
  "Azopt",
  "Azulfidine",
  "B",
  "B",
  "BOTOX",
  "BSS",
  "BUCCOLAM",
  "BUCCOLAM",
  "BUCCOLAM",
  "Babylax",
  "Bacillol",
  "Baclofen",
  "Baldriantinktur",
  "Baldriparan",
  "Batrafen",
  "Batrafen",
  "Benzbromaron",
  "Bepanthen",
  "Bepanthen",
  "Bepanthen",
  "Bepanthen",
  "Bepanthen",
  "Bepanthen",
  "Berberil",
  "Beriplast",
  "Beriplast",
  "Berirab",
  "Berirab",
  "Berodual",
  "Berodual",
  "Berotec",
  "Betahistin",
  "Betaisodona",
  "Betaisodona",
  "Betaisodona",
  "Betaisodona",
  "Betaisodona",
  "Betamann",
  "Betnesol",
  "Bezafibrat",
  "Bicalutamid",
  "Bifiteral",
  "Biocarn",
  "BisoHEXAL",
  "BisoHEXAL",
  "BisoHEXAL",
  "BisoHEXAL",
  "Blutegel",
  "Bosentan",
  "Braunovidon",
  "Brennnessel",
  "Bricanyl",
  "Bridion",
  "Brilique",
  "Brimica",
  "Bromazepam",
  "Bronchicum",
  "Bronchoretard",
  "Bronchoretard",
  "Bronchoretard",
  "Bronchoretard",
  "Bronchospasmin",
  "Budenobronch",
  "Budenofalk",
  "Budiair",
  "Buscopan",
  "Buscopan",
  "CAPSI",
  "CELEBREX",
  "CELEBREX",
  "CELESTAN",
  "CRH",
  "CYMBALTA",
  "CYMBALTA",
  "Calcipotriol",
  "Calcipotriol",
  "Calcium",
  "Calcium",
  "Calcium",
  "Calcium",
  "Calciumacetat",
  "Calciumacetat",
  "Calciumacetat",
  "Calciumfolinat",
  "Calciumfolinat",
  "Calciumgluconat",
  "Candesartan",
  "Candesartan",
  "Candesartan",
  "Candesartan",
  "Candio",
  "CaptoHEXAL",
  "CaptoHEXAL",
  "Carbimazol",
  "Carbimazol",
  "Carbostesin",
  "Carbostesin",
  "Carbostesin",
  "Carbostesin",
  "Carmen",
  "Carum",
  "Carvedilol",
  "Carvedilol",
  "Carvedilol",
  "Caspofungin",
  "Caspofungin",
  "Cecenu",
  "Cefepim",
  "Cefotaxim",
  "Cefotaxim",
  "Cefotaxim",
  "Ceftazidim",
  "Ceftriaxon",
  "Ceftriaxon",
  "Ceftriaxon",
  "Cefuroxim",
  "Cefuroxim",
  "CellCept",
  "CellCept",
  "CellCept",
  "Cellcept",
  "Celsentri",
  "Cephazolin",
  "Cernevit",
  "Certican",
  "Certican",
  "Certican",
  "Certican",
  "Certican",
  "Cetirizin",
  "Cetrotide",
  "Chloraldurat",
  "Chlorhexamed",
  "Chlorhexamed",
  "Chlorhexidindigluconat",
  "Chlorprothixen",
  "Chlorprothixen",
  "Ciatyl",
  "Ciatyl",
  "Ciloxan",
  "Cipralex",
  "Cipralex",
  "Cipramil",
  "CiproHEXAL",
  "CiproHEXAL",
  "Ciprobay",
  "Ciprofloxacin",
  "Ciprofloxacin",
  "Ciprofloxacin",
  "Circadin",
  "Citalopram",
  "Citalopram",
  "Citalopram",
  "Citalopram",
  "Clarithromycin",
  "Clarithromycin",
  "Clarithromycin",
  "Clarithromycin",
  "Clarium",
  "Clexane",
  "Clexane",
  "Clexane",
  "Clexane",
  "Clexane",
  "ClinOleic",
  "ClinOleic",
  "Clinda",
  "ClindaHEXAL",
  "ClindaHEXAL",
  "ClindaHEXAL",
  "Clindamycin",
  "Clobetasol",
  "Clobetasol",
  "Clobetasol",
  "Clonid",
  "Clonidin",
  "Clopidogrel",
  "Clyssie",
  "Cofact",
  "Coffeinum",
  "Coldastop",
  "Colestyramin",
  "ColistiFlex",
  "Combactam",
  "Combactam",
  "Combur",
  "Combur",
  "Combur",
  "Combur",
  "Conjuncain",
  "Contractubex",
  "Copal",
  "Copal",
  "Copaxone",
  "Cordichin",
  "Corneregel",
  "Corvaton",
  "Corvaton",
  "Corvaton",
  "Cotrim",
  "Cotrim",
  "Cotrim",
  "Cotrim",
  "Cotrim",
  "Coumadin",
  "Cromo",
  "Cromo",
  "Curosurf",
  "Custodiol",
  "Cutasept",
  "Cyclopentolat",
  "Cyklokapron",
  "DANTROLEN",
  "DAPSON",
  "DIFICLIR",
  "DIPROGENTA",
  "DIPROGENTA",
  "DIPROSALIC",
  "DYNEXAN",
  "Daivobet",
  "Daktar",
  "Daptomycin",
  "Daptomycin",
  "Daraprim",
  "Daxas",
  "Daxas",
  "Decoderm",
  "Decortin",
  "Decortin",
  "Decortin",
  "Decortin",
  "Decortin",
  "Decortin",
  "Decortin",
  "Decostriol",
  "Decostriol",
  "Defitelio",
  "Dekristol",
  "Dentinox",
  "Dermatop",
  "Dermatop",
  "Desderman",
  "Desderman",
  "Desderman",
  "Desferal",
  "Desitin",
  "Dexa",
  "Dexa",
  "Dexa",
  "Dexafluid",
  "Dexapos",
  "Dexdor",
  "Diarönt",
  "Diazepam",
  "Diazepam",
  "Diazepam",
  "Diazepam",
  "Diazepam",
  "Diazepam",
  "Diazepam",
  "Diazepam",
  "Dibenzyran",
  "Dibro",
  "Diclac",
  "Diclofenac",
  "Diclofenac",
  "Diclofenac",
  "Diclofenac",
  "Diclofenac",
  "Diflucan",
  "Digimerck",
  "Digimerck",
  "Digimerck",
  "Digitoxin",
  "DiltaHEXAL",
  "Diltiazem",
  "Dimaval",
  "Dipeptamin",
  "Distraneurin",
  "Distraneurin",
  "Ditripentat",
  "Dobutamin",
  "Dociton",
  "Dociton",
  "Dociton",
  "Dociton",
  "Dogmatil",
  "Dogmatil",
  "Dogmatil",
  "Dogmatil",
  "Dolantin",
  "Dolantin",
  "Dolo",
  "Dominal",
  "Donepezil",
  "Donepezil",
  "Dontisolon",
  "Dontisolon",
  "Dopamin",
  "Dormicum",
  "DorzoComp",
  "Dorzolamid",
  "Dostinex",
  "Doxazosin",
  "Doxazosin",
  "Doxepin",
  "Doxepin",
  "Doxepin",
  "DoxyHEXAL",
  "Dridase",
  "Driponin",
  "Duodart",
  "Duodart",
  "Duspatal",
  "Dysport",
  "Dysport",
  "Dytide",
  "ELIQUIS",
  "ELIQUIS",
  "EMB",
  "EMB",
  "EMB",
  "EMSER",
  "EPOPROSTENOL",
  "EREMFAT",
  "EREMFAT",
  "EREMFAT",
  "EREMFAT",
  "EREMFAT",
  "ERYTHROMYCIN",
  "EXJADE",
  "EXJADE",
  "Ebrantil",
  "Ebrantil",
  "Ebrantil",
  "Effentora",
  "Effentora",
  "Effentora",
  "Efflumidex",
  "Effortil",
  "Efient",
  "EinsAlpha",
  "EinsAlpha",
  "EinsAlpha",
  "Eklira",
  "Elebrato",
  "Elektrolyt",
  "Elidel",
  "Elontril",
  "Elontril",
  "Empressin",
  "Emselex",
  "Emtricitabin",
  "EnaHEXAL",
  "EnaHEXAL",
  "EnaHEXAL",
  "Enalapril",
  "Enalapril",
  "Enalapril",
  "Enantone",
  "Enbrel",
  "Enbrel",
  "Endo",
  "Endosgel",
  "Endoxan",
  "Entecavir",
  "Enthaarungscreme",
  "Entocort",
  "Entocort",
  "Entresto",
  "Entresto",
  "Entresto",
  "Envarsus",
  "Envarsus",
  "Envarsus",
  "Envarsus",
  "Envarsus",
  "Envarsus",
  "Envarsus",
  "Envarsus",
  "Envarsus",
  "Ephedrin",
  "Eplerenon",
  "Eplerenon",
  "Epoetin",
  "Epoetin",
  "Epoetin",
  "Epoetin",
  "Epoetin",
  "Epoetin",
  "Eprosartan",
  "Ergenyl",
  "Ergenyl",
  "Ergenyl",
  "Ergenyl",
  "Ergenyl",
  "Esemtan",
  "Eskazole",
  "Esomeprazol",
  "Etomidat",
  "Etoposid",
  "Etoricoxib",
  "Etoricoxib",
  "Etoricoxib",
  "Etoricoxib",
  "Eucerin",
  "Eucerin",
  "Eucerin",
  "Excipial",
  "Exelon",
  "Exelon",
  "Exelon",
  "Exelon",
  "Exemestan",
  "Exforge",
  "Exforge",
  "Exforge",
  "Ezetimib",
  "FORENE",
  "FOSTER",
  "FURACIN",
  "Fampyra",
  "Fasturtec",
  "Fasturtec",
  "Febuxostat",
  "Felocor",
  "Felocor",
  "Fenistil",
  "Fenistil",
  "Fenistil",
  "Fentanyl",
  "Fentanyl",
  "Fentanyl",
  "Fentanyl",
  "Fentanyl",
  "Fentanyl",
  "Fentanyl",
  "Ferinject",
  "Ferrlecit",
  "Ferrlecit",
  "Fexofenaderm",
  "Fexofenaderm",
  "Filgrastim",
  "Filgrastim",
  "Finalgon",
  "Finasterid",
  "Flammazine",
  "Flecainid",
  "Floxal",
  "Floxal",
  "Floxal",
  "Fluanxol",
  "Fluanxol",
  "Fluanxol",
  "Fluclox",
  "Fluclox",
  "Fluconazol",
  "Fluconazol",
  "Fluconazol",
  "Fluconazol",
  "Fluconazol",
  "Fluconazol",
  "Fludarabinphosphat",
  "Fluimucil",
  "Flumazenil",
  "Fluomizin",
  "Fluorescein",
  "Fluoxetin",
  "Flutide",
  "Fluvastatin",
  "Fluvastatin",
  "Fluvoxamin",
  "Folsäure",
  "Folverlan",
  "Foradil",
  "Fortecortin",
  "Fortecortin",
  "Fortecortin",
  "Fortecortin",
  "Fortecortin",
  "Fortecortin",
  "Fortecortin",
  "Forxiga",
  "Forxiga",
  "Fosfomycin",
  "Fosrenol",
  "Fosrenol",
  "Fosrenol",
  "Foster",
  "FrekaVit",
  "Frisium",
  "Fucidine",
  "Fulvestrant",
  "Fungizid",
  "Fungizone",
  "Furosemid",
  "Furosemid",
  "Furosemid",
  "Furosemid",
  "Furosemid",
  "Fuzeon",
  "Fycompa",
  "Fycompa",
  "Fycompa",
  "Fycompa",
  "Fycompa",
  "GELITA",
  "GENTAMICIN",
  "GRANOCYTE",
  "GRANOCYTE",
  "Gabapentin",
  "Gabapentin",
  "Gabapentin",
  "Gabapentin",
  "Gadovist",
  "Ganciclovir",
  "Gastrografin",
  "Gastrolux",
  "Gastrozepin",
  "Gelafundin",
  "Gelita",
  "GeloMyrtol",
  "Gent",
  "Gent",
  "Gigasept",
  "Gilurytmal",
  "Gingicain",
  "Gingium",
  "Gingium",
  "Glib",
  "Glimepirid",
  "Glimepirid",
  "Gliolan",
  "Glivec",
  "Glivec",
  "GlucaGen",
  "Glucose",
  "Glucose",
  "Glucose",
  "Glucose",
  "Glucose",
  "Glucose",
  "Glucose",
  "Glucose",
  "Glucose",
  "Glucose",
  "Glucose",
  "Glucose",
  "Glucose",
  "Glucose",
  "Glucose",
  "Glucose",
  "Glycilax",
  "Grafalon",
  "Grafalon",
  "Granisetron",
  "Granisetron",
  "Granisetron",
  "Gutron",
  "Guttaplast",
  "H",
  "HALDOL",
  "HALDOL",
  "HALDOL",
  "HBVAXPRO",
  "HBVAXPRO",
  "HCT",
  "HCT",
  "HCT",
  "HCT",
  "HEUMANN",
  "HUMAN",
  "HUMAN",
  "HYDROCORTISON",
  "HYLASE",
  "Haemoccult",
  "Haemopressin",
  "Haloperidol",
  "Haloperidol",
  "Heilo",
  "Hepa",
  "Hepa",
  "Hepa",
  "Heparin",
  "Heparin",
  "Heparin",
  "Histakut",
  "Histoacryl",
  "Humalog",
  "Human",
  "Human",
  "Humanalbin",
  "Humanalbin",
  "Huminsulin",
  "Huminsulin",
  "Huminsulin",
  "Hydergin",
  "Hydrierungsbeutel",
  "Hydrierungsbeutel",
  "Hydrierungsbeutel",
  "Hydrierungsbeutel",
  "Hydrierungsbeutel",
  "Hydrierungsbeutel",
  "Hydrierungsbeutel",
  "Hydrocortison",
  "Hydrocutan",
  "Hydromorphon",
  "IBU",
  "ILUVIEN",
  "IMODIUM",
  "IMODIUM",
  "INFECTOCILLIN",
  "INFECTOCORTISEPT",
  "INFECTOFOS",
  "INFECTOFOS",
  "INFECTOMYCIN",
  "INFECTOOPTICEF",
  "INFECTOTRIMET",
  "INVANZ",
  "IS",
  "ISENTRESS",
  "ISOZID",
  "ISOZID",
  "IVEMEND",
  "Ibandronsäure",
  "Ibandronsäure",
  "Iberogast",
  "Ibu",
  "IbuHEXAL",
  "Ibuflam",
  "Ibuprofen",
  "Ibuprofen",
  "Ichtholan",
  "Ichtholan",
  "Imap",
  "Imipramin",
  "Imurek",
  "Incidin",
  "Infanrix",
  "InfectoKrupp",
  "Infectoscab",
  "Inovelon",
  "Inovelon",
  "Instillagel",
  "Instillagel",
  "Intal",
  "IpraBronch",
  "Irenat",
  "Iruxol",
  "Ismo",
  "Isotone",
  "Isotone",
  "Isotone",
  "Isotone",
  "Isotone",
  "Isotone",
  "Isotone",
  "Isotone",
  "Isotone",
  "Isotone",
  "Isotonische",
  "Isotonische",
  "Isotonische",
  "Isotonische",
  "Isotonische",
  "Isotonische",
  "Ivabradin",
  "Ixoten",
  "JURNISTA",
  "JURNISTA",
  "Jacutin",
  "Janumet",
  "Janumet",
  "Januvia",
  "Januvia",
  "Januvia",
  "Jardiance",
  "Jardiance",
  "Jatrosom",
  "Jelliproct",
  "Jodetten",
  "Jodid",
  "KA",
  "KALINOR",
  "KALINOR",
  "KIOVIG",
  "KIOVIG",
  "KIOVIG",
  "KNOCHENWACHS",
  "Kabiven",
  "Kaliumchlorid",
  "Kaliumchlorid",
  "Kamillosan",
  "Kamillosan",
  "Kanamycin",
  "Kanamycin",
  "Ketanest",
  "Ketanest",
  "Kochsalzlösung",
  "Kochsalzlösung",
  "Kochsalzlösung",
  "Kodan",
  "Kodan",
  "Kohle",
  "Konakion",
  "Konakion",
  "Korsolex",
  "Korsolex",
  "Kreon",
  "Kreon",
  "Kreon",
  "L",
  "L",
  "L",
  "L",
  "L",
  "L",
  "L",
  "L",
  "L",
  "L",
  "LOTRICOMB",
  "LOTRICOMB",
  "Lamictal",
  "Lamictal",
  "Lamictal",
  "Lamictal",
  "Lamivudin",
  "Lamotrigin",
  "Lamotrigin",
  "Lamotrigin",
  "Lanicor",
  "Lanicor",
  "Lanitop",
  "Lansinoh",
  "Lansinoh",
  "Lantarel",
  "Lantarel",
  "Lantarel",
  "Lantarel",
  "Lantarel",
  "Lasix",
  "Lavanid",
  "Laxans",
  "Laxans",
  "Laxans",
  "Lecicarbon",
  "Lefax",
  "Leflunomid",
  "Leflunomid",
  "Legalon",
  "Leponex",
  "Leponex",
  "Leponex",
  "LetroHEXAL",
  "Leukase",
  "Leukeran",
  "Levemir",
  "Levetiracetam",
  "Levetiracetam",
  "Levetiracetam",
  "Levetiracetam",
  "Levetiracetam",
  "Levofloxacin",
  "Levofloxacin",
  "Levofloxacin",
  "Lidocard",
  "Limptar",
  "Linezolid",
  "Linezolid",
  "Linola",
  "Linola",
  "Linola",
  "Linola",
  "Lioresal",
  "Lioresal",
  "Lioresal",
  "Lioresal",
  "Lipiodol",
  "Lisinopril",
  "Lisinopril",
  "Lisinopril",
  "Lisinopril",
  "Lisinopril",
  "Lisinopril",
  "Lisinopril",
  "Lisinopril",
  "Lisinopril",
  "Lixiana",
  "Lixiana",
  "Lixiana",
  "Lonolox",
  "Lonolox",
  "Lopedium",
  "Loratadin",
  "Lormetazepam",
  "Losartan",
  "Losartan",
  "Luminaletten",
  "Luminal",
  "Luminal",
  "Lygal",
  "Lygal",
  "Lyostypt",
  "Lysthenon",
  "MCP",
  "MCP",
  "MEDCOAT",
  "MESNA",
  "MESNA",
  "MG",
  "MILNAneuraX",
  "MILRINON",
  "MINIRIN",
  "MINIRIN",
  "MINPROG",
  "MOVICOL",
  "MOVIPREP",
  "MST",
  "MST",
  "MST",
  "MST",
  "MST",
  "MST",
  "MST",
  "MST",
  "MULTAQ",
  "Macrogol",
  "Madopar",
  "Madopar",
  "Madopar",
  "Magnesium",
  "Magnesium",
  "Magnesium",
  "Magnesiumsulfat",
  "Maprotilin",
  "Marcumar",
  "Mecain",
  "Melleril",
  "Melperon",
  "Melperon",
  "Melphalan",
  "Menveo",
  "Mercaptopurin",
  "Meropenem",
  "Meropenem",
  "Meropenem",
  "Mestinon",
  "Mestinon",
  "Mestinon",
  "Mestinon",
  "Metalcaptase",
  "Methaliq",
  "Methocel",
  "Methylprednisolut",
  "Methylprednisolut",
  "Methylprednisolut",
  "Methylprednisolut",
  "Methylthioniniumchlorid",
  "Metoprolol",
  "Metoprololsuccinat",
  "Metoprololsuccinat",
  "Metoprololsuccinat",
  "Metronidazol",
  "Metronidazol",
  "Microgynon",
  "Microlax",
  "Micropaque",
  "Micropaque",
  "Microtrast",
  "Midazolam",
  "Midazolam",
  "Midazolam",
  "Midazolam",
  "Midazolam",
  "Midazolam",
  "Mikrozid",
  "Mimpara",
  "Mimpara",
  "Minocyclin",
  "Minocyclin",
  "Minprostin",
  "Minprostin",
  "Mirtazapin",
  "Mirtazapin",
  "Mirtazapin",
  "Mivacron",
  "Mobilat",
  "Modigraf",
  "Modigraf",
  "Momecutan",
  "Momecutan",
  "Momecutan",
  "MometaHEXAL",
  "Monoprost",
  "Montelukast",
  "Moronal",
  "Moronal",
  "Moronal",
  "Morphin",
  "Morphin",
  "Morphin",
  "Motilium",
  "Motilium",
  "Moxifloxacin",
  "Moxifloxacin",
  "Moxonidin",
  "Moxonidin",
  "Moxonidin",
  "Moxonidin",
  "Moxonidin",
  "Moxonidin",
  "Moxonidin",
  "Moxonidin",
  "Moxonidin",
  "Mucofalk",
  "Mucositis",
  "Mucosolvan",
  "Mucosolvan",
  "Mucosolvan",
  "Multibionta",
  "Multilind",
  "Mycamine",
  "Mycamine",
  "Mycobutin",
  "Mydriaticum",
  "Myfortic",
  "Myfortic",
  "Mylepsinum",
  "NAC",
  "NAC",
  "NATRIUMTHIOSULFAT",
  "NATRIUMTHIOSULFAT",
  "NEOSTIG",
  "NEVANAC",
  "NIMODIPIN",
  "NIPRUSS",
  "Nagel",
  "Nalador",
  "Naloxon",
  "Naltrexon",
  "Naproxen",
  "NasenSpray",
  "Natriumchlorid",
  "Natriumchlorid",
  "Natriumchlorid",
  "Natriumchlorid",
  "Natriumglycerophosphat",
  "Natriumhydrogencarbonat",
  "Natriumhydrogencarbonat",
  "Natriumhydrogencarbonat",
  "Natriumphosphat",
  "Nebivolol",
  "Nefrocarnit",
  "Neo",
  "NeoRecormon",
  "Neosynephrin",
  "Neosynephrin",
  "Nephrotect",
  "Nephrotrans",
  "Nephrotrans",
  "Nepresol",
  "Nepresol",
  "Neribas",
  "Neribas",
  "Nerisona",
  "Nerisona",
  "Nerven",
  "Neulasta",
  "Neupro",
  "Neupro",
  "Neupro",
  "Neupro",
  "Neupro",
  "Neupro",
  "Neurocil",
  "Neurocil",
  "Neurocil",
  "Neurotrat",
  "Nexium",
  "Nexium",
  "Nicotinsäureamid",
  "Nifedipin",
  "Nifedipin",
  "Nifedipin",
  "Nifedipin",
  "Nimbex",
  "Nimbex",
  "Nimotop",
  "Nitoman",
  "Nitrendipin",
  "Nitrendipin",
  "Nitrofurantoin",
  "Nitrolingual",
  "Nitrolingual",
  "Nitroxolin",
  "Nizoral",
  "Norvir",
  "Novaminsulfon",
  "Novaminsulfon",
  "Novaminsulfon",
  "Novaminsulfon",
  "Novesine",
  "NovoNorm",
  "NovoNorm",
  "NovoNorm",
  "NovoRapid",
  "Novodigal",
  "Novodigal",
  "Novothyral",
  "Noxafil",
  "Noxafil",
  "Nplate",
  "Nplate",
  "NuTRIflex",
  "NuTRIflex",
  "NuTRIflex",
  "Nubral",
  "Nurofen",
  "Nurofen",
  "Nurofen",
  "ODM",
  "Octeniderm",
  "Octreotid",
  "Octreotid",
  "Octreotid",
  "Ocuflur",
  "Olimel",
  "Olimel",
  "Olmesartan",
  "Olmesartan",
  "Olmesartan",
  "Omacor",
  "Ondansetron",
  "Ondansetron",
  "Ondansetron",
  "Ondansetron",
  "Ondansetron",
  "Onglyza",
  "Opipramol",
  "Opraclean",
  "Opraclean",
  "Opraclean",
  "Optiderm",
  "Oralpädon",
  "Oramorph",
  "Orfiril",
  "Orfiril",
  "Orfiril",
  "Orfiril",
  "Orfiril",
  "Orgaran",
  "Ortoton",
  "Osmofundin",
  "Osmofundin",
  "Ospolot",
  "OsvaRen",
  "Otalgan",
  "Otobacid",
  "Otowaxol",
  "Otriven",
  "Otriven",
  "Otriven",
  "Otriven",
  "Otriven",
  "Ovestin",
  "Ovestin",
  "Ovestin",
  "Ovitrelle",
  "Oxane",
  "Oxazepam",
  "Oxcarbazepin",
  "Oxcarbazepin",
  "Oxis",
  "Oxis",
  "Oxygesic",
  "Oxygesic",
  "Oxygesic",
  "Oxygesic",
  "Oxygesic",
  "Oxygesic",
  "Oxytocin",
  "Oxytocin",
  "Ozurdex",
  "PANTOPRAZOL",
  "PC",
  "PERITRAST",
  "PFEFFERMINZOEL",
  "PHYSIOGEL",
  "PICOPREP",
  "PK",
  "PK",
  "PNEUMOVAX",
  "Palacos",
  "Palacos",
  "Palacos",
  "Palexia",
  "Palexia",
  "Palexia",
  "Palexia",
  "Palexia",
  "Palladon",
  "Palladon",
  "Palladon",
  "Palladon",
  "Palladon",
  "Palladon",
  "Palladon",
  "Palladon",
  "Pamifos",
  "Pamifos",
  "Pamifos",
  "Pamifos",
  "Panoral",
  "Panoral",
  "Panthenol",
  "Pantoprazol",
  "Pantoprazol",
  "Paracefan",
  "Paracetamol",
  "Paracetamol",
  "Paracetamol",
  "Paracetamol",
  "Paracetamol",
  "Paracetamol",
  "Paracetamol",
  "Paracetamol",
  "Paracetamol",
  "Paracodin",
  "Parkopan",
  "Paroxetin",
  "Partusisten",
  "Paveron",
  "Pedea",
  "PenHEXAL",
  "Penicillin",
  "Penicillin",
  "Pentacarinat",
  "Pentalong",
  "Pentoxifyllin",
  "Perazin",
  "Perazin",
  "Perocur",
  "Petinutin",
  "Petnidan",
  "Peyona",
  "Pfefferminzblätter",
  "Phenhydan",
  "Phenhydan",
  "Phenylephrin",
  "Phosphonorm",
  "Phosphonorm",
  "Phosphonorm",
  "Phoxilium",
  "Pilomann",
  "Pipamperon",
  "Pipamperon",
  "Piperacillin",
  "Piperacillin",
  "Piperacillin",
  "Piracetam",
  "Piretanid",
  "Piritramid",
  "Piritramid",
  "Plavix",
  "Polyspectran",
  "Posterisan",
  "Posterisan",
  "Pradaxa",
  "Pradaxa",
  "Pradaxa",
  "Pramipexol",
  "Pramipexol",
  "Pramipexol",
  "Pramipexol",
  "Pravastatin",
  "Pravastatin",
  "Pravastatin",
  "Pravidel",
  "Predni",
  "Pregabalin",
  "Pregabalin",
  "Pregabalin",
  "Pregabalin",
  "Pregabalin",
  "Presinol",
  "Prevenar",
  "Prismocal",
  "Prismocitrate",
  "Privigen",
  "Privigen",
  "Prograf",
  "Prograf",
  "Prograf",
  "Prograf",
  "Prontoderm",
  "Prontoderm",
  "Prontoral",
  "Prontosan",
  "Proparakain",
  "Propiverin",
  "Propofol",
  "Propofol",
  "Propofol",
  "Prostacure",
  "Protamin",
  "Protaphane",
  "Protopic",
  "Pulmozyme",
  "Puri",
  "Purisole",
  "Pylera",
  "Pyralvex",
  "Pyrazinamid",
  "PädiaSalin",
  "Pädiatrische",
  "Pädiatrische",
  "Pädiatrische",
  "Quensyl",
  "Quetiapin",
  "Quetiapin",
  "Quetiapin",
  "Quetiapin",
  "Quetiapin",
  "Quetiapin",
  "Quilonum",
  "Qutenza",
  "RAPIFEN",
  "REBETOL",
  "REMICADE",
  "REQUIP",
  "REQUIP",
  "REQUIP",
  "REQUIP",
  "REQUIP",
  "RESORBA",
  "RESORBA",
  "RESORBA",
  "RISPERDAL",
  "RISPERDAL",
  "RISPERDAL",
  "Ramipril",
  "Ramipril",
  "Ramipril",
  "Ranexa",
  "Ranexa",
  "Ranitidin",
  "Ranitidin",
  "Rantudil",
  "Rapamune",
  "Rapamune",
  "Rapamune",
  "Rasilez",
  "Rectodelt",
  "Reducto",
  "Refobacin",
  "Refobacin",
  "Relefact",
  "Relistor",
  "Remestan",
  "Remestan",
  "Remifemin",
  "Remifemin",
  "Remsima",
  "Reparil",
  "Resochin",
  "Resolor",
  "Resolor",
  "Resonium",
  "Restex",
  "Retrovir",
  "Revinty",
  "Revinty",
  "Rhophylac",
  "Riluzol",
  "Ringer",
  "Ringer",
  "Ringer",
  "Ringer",
  "Riopan",
  "Risedron",
  "Risperidon",
  "Risperidon",
  "Risperidon",
  "Risperidon",
  "Risperidon",
  "Ritalin",
  "Rivotril",
  "Rivotril",
  "Rivotril",
  "Rivotril",
  "RoActemra",
  "RoActemra",
  "RoActemra",
  "Robinul",
  "Rocuroniumbromid",
  "Ropivacain",
  "Ropivacain",
  "Ropivacain",
  "Rosuvastatin",
  "Rytmonorm",
  "Rytmonorm",
  "SEKUDRILL",
  "SEMPERA",
  "SIMBRINZA",
  "SMOFlipid",
  "SOMSANIT",
  "SOTALOL",
  "SPONGOSTAN",
  "STOMAHESIVE",
  "STOMAHESIVE",
  "STRATTERA",
  "STRATTERA",
  "SUSTIVA",
  "Sab",
  "Sabril",
  "Sabril",
  "Salbutamol",
  "Salbutamol",
  "Salofalk",
  "Salofalk",
  "Salofalk",
  "Salofalk",
  "Salofalk",
  "Salofalk",
  "Salofalk",
  "Salofalk",
  "Salviathymol",
  "Samsca",
  "Sandimmun",
  "Sandimmun",
  "Sandimmun",
  "Sandimmun",
  "Sandimmun",
  "Sandimmun",
  "Sandimmun",
  "Saseem",
  "Scandicain",
  "Scandicain",
  "Scopoderm",
  "Seebri",
  "Sekusept",
  "Sekusept",
  "Selectomycin",
  "Sempera",
  "Sensiva",
  "Sensiva",
  "Septopal",
  "Septopal",
  "Septopal",
  "Septopal",
  "Serdolect",
  "Serdolect",
  "Serevent",
  "Sertralin",
  "Sertralin",
  "Sevelamercarbonat",
  "Sevorane",
  "Sevredol",
  "Sevredol",
  "Sidroga",
  "Sildenafil",
  "Silonda",
  "Simdax",
  "Simethicon",
  "Simulect",
  "Simulect",
  "SimvaHEXAL",
  "SimvaHEXAL",
  "SimvaHEXAL",
  "Sinupret",
  "Sinupret",
  "Sinupret",
  "Siofor",
  "Siofor",
  "Siofor",
  "Skinoren",
  "SmofKabiven",
  "Sobelin",
  "Solacutan",
  "Solcoseryl",
  "Solian",
  "Solian",
  "Solian",
  "Solifenacin",
  "Solifenacin",
  "Solosin",
  "Solu",
  "Solu",
  "Solu",
  "Solu",
  "Solu",
  "Somatostatin",
  "SonoVue",
  "Sormodren",
  "Sotalol",
  "Sotalol",
  "Spasmex",
  "Spasmo",
  "Spiolto",
  "Spiriva",
  "Spironolacton",
  "Spironolacton",
  "Stalevo",
  "Stalevo",
  "Stalevo",
  "Stalevo",
  "Stangyl",
  "Stangyl",
  "Stangyl",
  "Staphylex",
  "Staurodorm",
  "Sterillium",
  "Sterillium",
  "Sterillium",
  "Sterofundin",
  "Sterofundin",
  "Sterofundin",
  "Stilnox",
  "Sucrabest",
  "Sufenta",
  "Sufenta",
  "Sulfadiazin",
  "Sulmycin",
  "Sulmycin",
  "Sultanol",
  "Sumatriptan",
  "Sumatriptan",
  "Suprane",
  "Suprarenin",
  "Sweatosan",
  "Sycrest",
  "Symbicort",
  "Symbicort",
  "Synacthen",
  "Synacthen",
  "Synagis",
  "Synagis",
  "Syrea",
  "TABOTAMP",
  "TARDOCILLIN",
  "TARGIN",
  "TARGIN",
  "TARGIN",
  "TARGIN",
  "TEMGESIC",
  "TEMGESIC",
  "THAM",
  "TISSEEL",
  "TOLUIDINBLAU",
  "TOVIAZ",
  "TRH",
  "TYSABRI",
  "TachoSil",
  "TachoSil",
  "TachoSil",
  "Takipril",
  "Tambocor",
  "Tamoxifen",
  "Tannolact",
  "Targocid",
  "Targocid",
  "Taurolock",
  "Tavegil",
  "Tavegil",
  "Tavor",
  "Tavor",
  "Tavor",
  "Td",
  "Tears",
  "Tegretal",
  "Tegretal",
  "Tegretal",
  "Telebrix",
  "Telmisartan",
  "Telmisartan",
  "Telmisartan",
  "Telzir",
  "Temodal",
  "Temozolomide",
  "Temozolomide",
  "Temozolomide",
  "Temozolomide",
  "Temozolomide",
  "Tenofovirdisoproxil",
  "Terbinafin",
  "Tetagam",
  "Thiamazol",
  "Thiamazol",
  "Thioctacid",
  "Thioguanin",
  "Thiopental",
  "Thrombareduct",
  "Thyrogen",
  "Thyronajod",
  "Thyronajod",
  "Thyronajod",
  "Thyrotardin",
  "Tiaprid",
  "Tigecyclin",
  "Tilidin",
  "Tilidin",
  "Timonil",
  "Timonil",
  "Tim",
  "Tim",
  "Tirofiban",
  "Tivicay",
  "Tivicay",
  "Tizanidin",
  "Tizanidin",
  "Tobramaxin",
  "Tolperison",
  "Tolterodin",
  "Topamax",
  "Topamax",
  "Topamax",
  "Torasemid",
  "Torasemid",
  "Torasemid",
  "Torem",
  "Toxogonin",
  "Tracleer",
  "Tramadol",
  "Tramadol",
  "Tramadol",
  "Tramal",
  "Tramal",
  "Tramal",
  "Tramal",
  "Tranexamsäure",
  "Tranexamsäure",
  "Transpulmin",
  "Transpulmin",
  "Transtec",
  "Transtec",
  "Tranxilium",
  "Traumon",
  "Travocort",
  "Trazodon",
  "Trental",
  "Trental",
  "Tresiba",
  "Trevilor",
  "Trevilor",
  "Trevilor",
  "TriamHEXAL",
  "TriamHEXAL",
  "Tromcardin",
  "Tuberkulin",
  "Turixin",
  "Tutofusin",
  "UMAN",
  "UMAN",
  "URICULT",
  "Ubretid",
  "Ubretid",
  "Ultibro",
  "Ultiva",
  "Ultiva",
  "Ultiva",
  "Ultracain",
  "Ultracain",
  "Ultracain",
  "Ultracain",
  "Ultracain",
  "Ultracain",
  "Ultracain",
  "Ultracortenol",
  "Ultravist",
  "Ultravist",
  "Ultravist",
  "Ultravist",
  "Ultravist",
  "Ultravist",
  "Ultravist",
  "Ultravist",
  "Unacid",
  "Unacid",
  "Unacid",
  "Unacid",
  "Unguentum",
  "Unizink",
  "Unizink",
  "Uralyt",
  "Urapidil",
  "Urbason",
  "Uro",
  "Uromitexan",
  "Ursofalk",
  "Ursofalk",
  "Ursofalk",
  "VASELINE",
  "VERMOX",
  "VIGAMOX",
  "Valcyte",
  "Valdoxan",
  "Valganciclovir",
  "Valoron",
  "Valtrex",
  "Vaselin",
  "Vasomotal",
  "Vecuronium",
  "Venlafaxin",
  "Venofer",
  "Ventolair",
  "VeraHEXAL",
  "VeraHEXAL",
  "VeraHEXAL",
  "VeraHEXAL",
  "Vergentan",
  "Vergentan",
  "Verrumal",
  "Versatis",
  "Vertigo",
  "Vesanoid",
  "Viani",
  "Viani",
  "Viani",
  "Viani",
  "Vidisept",
  "Vigantoletten",
  "Vigantoletten",
  "Vimpat",
  "Vimpat",
  "Vimpat",
  "Vimpat",
  "Vimpat",
  "Viramune",
  "VitA",
  "Vitalipid",
  "Vitamin",
  "Vitamin",
  "Vitamin",
  "Vitamin",
  "Vitamin",
  "Vitamin",
  "Vitamin",
  "Vitamin",
  "Vitamin",
  "Vitarenal",
  "Volon",
  "Volon",
  "Volon",
  "Voltaren",
  "Vomacur",
  "Vomex",
  "Vomex",
  "Vomex",
  "Vomex",
  "Voriconazol",
  "Voriconazol",
  "Voriconazol",
  "X",
  "XGEVA",
  "Xadago",
  "Xailin",
  "Xalacom",
  "Xalatan",
  "Xarelto",
  "Xarelto",
  "Xarelto",
  "Xeomin",
  "Xeplion",
  "Xeplion",
  "Xifaxan",
  "Xifaxan",
  "Xolair",
  "Xolair",
  "Xolair",
  "Xomolix",
  "Xylocain",
  "Xylocain",
  "Xylocain",
  "Xylocain",
  "Xylonest",
  "Xylonest",
  "Xylonest",
  "Xylonest",
  "Xylonest",
  "Xylonest",
  "Xylonest",
  "ZELDOX",
  "Zavedos",
  "Zeffix",
  "Ziagen",
  "Zineryt",
  "Zofran",
  "Zofran",
  "Zoladex",
  "Zoladex",
  "Zoledronsäure",
  "ZonisaHEXAL",
  "ZonisaHEXAL",
  "ZonisaHEXAL",
  "Zopiclon",
  "Zopiclon",
  "Zostex",
  "Zovirax",
  "Zyklolat",
  "Zymafluor",
  "Zyprexa",
  "Zyprexa",
  "Zyprexa",
  "ben",
  "bicaNorm",
  "desmanol",
  "desmanol",
  "desmanol",
  "ellaOne",
  "elmex",
  "ferro",
  "ferro",
  "ferro",
  "frubiase",
  "frubiase",
  "isicom",
  "isicom",
  "isicom",
  "isicom",
  "isoket",
  "isoket",
  "isoket",
  "isoket",
  "nikofrenon",
  "nikofrenon",
  "nikofrenon",
  "octenisept",
  "prostavasin",
  "sab",
  "schülke",
  "selenase",
  "selenase"]